# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ObjectivePgpTest' do

pod 'OpenSSL-Universal', :git => 'https://github.com/krzyzanowskim/OpenSSL.git', :branch => :master
pod 'ObjectivePGP', :git => 'https://github.com/krzyzanowskim/ObjectivePGP.git', :branch => :master
pod 'UNNetPGP', :podspec => 'https://raw.github.com/upnext/unnetpgp/master/UNNetPGP.podspec'

end

target 'ObjectivePgpTest' do

end

